# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ride
title_short: Ride
description: >
  Self driving car service
baseurl: ""
url: "http://erides.io"
twitter_username:
github_username:  mttjohnson
#sass:
#    style: :compressed

# Build settings
markdown: kramdown
